name: Build iOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-ios.yml'
      - 'example/ios'
      - 'packages/react-native-nitro-image/nitrogen'
      - 'packages/react-native-nitro-image/cpp'
      - 'packages/react-native-nitro-image/ios'
      - 'packages/react-native-nitro-modules/cpp'
      - 'packages/react-native-nitro-modules/ios'
      - '**/Podfile.lock'
      - '**/*.podspec'
      - '**/react-native.config.js'
      - '**/nitro.json'
  pull_request:
    paths:
      - '.github/workflows/build-ios.yml'
      - 'example/ios'
      - 'packages/react-native-nitro-image/nitrogen'
      - 'packages/react-native-nitro-image/cpp'
      - 'packages/react-native-nitro-image/ios'
      - 'packages/react-native-nitro-modules/cpp'
      - 'packages/react-native-nitro-modules/ios'
      - '**/Podfile.lock'
      - '**/*.podspec'
      - '**/react-native.config.js'
      - '**/nitro.json'

jobs:
  build:
    name: Build iOS Example App
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install --frozen-lockfile

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: example/ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        working-directory: example/ios
        run: pod install
      - name: Build App
        working-directory: example/ios
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace NitroExample.xcworkspace \
          -scheme NitroExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
